ALTER TABLE "Project"
  ADD COLUMN IF NOT EXISTS "allowedRadiusMeters" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "SiteVisit"
  ADD COLUMN IF NOT EXISTS "salespersonLatitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "salespersonLongitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "gpsAccuracyMeters" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "gpsTimestamp" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "projectLatitudeAtCompletion" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "projectLongitudeAtCompletion" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "distanceFromProjectMeters" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "locationVerified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "locationVerifiedAt" TIMESTAMP(3);
